AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  InstanceId:
    Type: String
    Description: 'InstanceId of the EC2 instance'

  DatabaseEndpoint:
    Type: String
    Description: 'Endpoint of the database'

  PrivateIps:
    Type: String
    Description: 'Private IPs of the EC2 instance'

  PrimaryIp:
    Type: String
    Description: 'Private IPs of the EC2 instance'

  DomainName:
    Type: String
    Description: Name of the server
    
  Containername:
    Type: String
    Description: Name of the container
    
Resources:
  LambdaFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: wordpressautomation
      Runtime: 'python3.8'
      Handler: index.lambda_handler
      Code: 
        S3Bucket: wordpressautomation
        S3Key: nginxcode.zip
      Role: arn:aws:iam::059449770494:role/lambdaforwps
      Environment:
        Variables:
          InstanceId: !Ref InstanceId
          DatabaseEndpoint: !Ref DatabaseEndpoint
          PrivateIps: !Ref PrivateIps
          PrimaryIp: !Ref PrimaryIp
          DomainName: !Ref DomainName
          Containername: !Ref Containername
      Timeout: 60
      
